image: "python:3.9"

stages:
  - test
  - deploy

.before_script_template:
  before_script:
    - pip install --upgrade pip
    - pip install poetry
    - poetry install

test:
  extends: .before_script_template
  stage: test
  script:
    - poetry run pytest -v

deploy_test:
  extends: .before_script_template
  stage: deploy
  script:
    - poetry build
    - poetry publish --repository=testpypi --username=$PYPI_USER --password=$PYPI_PWD 
  only:
    - tags

deploy_prod:
  extends: .before_script_template
  stage: deploy
  script:
    - poetry build
    - poetry publish --username=$PYPI_USER --password=$PYPI_PWD
  only:
    - tags
