image: "python:3.9"

stages:
  - test
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  CI_REGISTRY_IMAGE: ebispot/gwas-sumstats-tools


.before_script_template:
  before_script:
    - pip install --upgrade pip
    - pip install poetry
    - poetry install

test:
  extends: .before_script_template
  stage: test
  script:
    - poetry run pytest -v

deploy_test:
  extends: .before_script_template
  stage: deploy
  script:
    - poetry config repositories.testpypi https://test.pypi.org/legacy/
    - poetry build
    - poetry publish --repository=testpypi --username=$PYPI_USER --password=$PYPI_PWD 
  only:
    - tags

build:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
   - echo "$DOCKER_HUB_PASSWORD" > dhpw.txt
   - docker login -u "${DOCKER_HUB_USER}" --password-stdin < dhpw.txt docker.io
   - docker pull $CI_REGISTRY_IMAGE:latest
   - docker build --cache-from $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
   - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  tags:
    - gwas
  only:
    - master
    - dev

build_release:
  image: docker:latest
  services:
    - docker:dind
  variables:
    GIT_STRATEGY: none
  stage: build
  script:
   - echo "$DOCKER_HUB_PASSWORD" > dhpw.txt
   - docker login -u "${DOCKER_HUB_USER}" --password-stdin < dhpw.txt
   - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
   - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
   - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
   - docker push $CI_REGISTRY_IMAGE:latest
   - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  tags:
    - gwas
  only:
    - tags

deploy_prod:
  extends: .before_script_template
  stage: deploy
  script:
    - poetry build
    - poetry publish --username=$PYPI_USER --password=$PYPI_PWD
  only:
    - tags
