[project]
name = "gwas-sumstats-tools"
version = "1.0.24"
description = ""
authors = [
    {name = "jdhayhurst", email = "jhayhurst@ebi.ac.uk"},
    {name = "yueji", email = "jiyue1214@gmail.com"},
]
readme = "README.md"
requires-python = ">=3.9,<3.12"
dependencies = [
    "petl>=1.7.12,<2",
    "requests>=2.28.2,<3",
    "pyyaml>=6.0,<7",
    "pydantic>=1.10.4,<2",
    "typer[all]>=0.7.0,<1",
    "pandera>=0.13.4,<0.14",
    "pandas==1.5.3",
    "numpy<2",
    "ruamel-yaml==0.17.32",
    "bsub>=0.3.5,<1",
]

[project.scripts]
gwas-ssf = "gwas_sumstats_tools.cli:app"

[dependency-groups]
dev = [
    "flake8>=6.0.0,<7",
    "pytest>=7.2.1,<8",
    "hypothesis>=6.68.2,<7",
    "pytest-mock>=3.10.0,<4",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/gwas_sumstats_tools"]
