apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.k8Namespace }}
  labels:
    app: {{ .Values.service.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.service.name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
